version: "3"

services:
  node:
    container_name: node
    build: ./services/node
    image: node:ts
    volumes:
      - node:/usr/app/srcs
    networks:
      - my_network
    restart: always
  nest:
    container_name: nest
    build: ./services/nest
    image: nest:ts
    volumes:
      - nest:/usr/app/srcs
    networks:
      - my_network
    restart: always

volumes:
  node:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/srcs/node'
  nest:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/srcs/nest'

networks:
  my_network: 
    driver: bridge