version: "3"

services:
  node:
    container_name: node
    build: ./node
    image: node:ts
    volumes:
      - srcs:/usr/app/srcs
    networks:
      - my_network
    restart: always

volumes:
  srcs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${HOME}/Desktop/transcendence/srcs'

networks:
  my_network: 
    driver: bridge