version: "3"

services:
  react:
    container_name: react
    build: ./services/react
    image: react:ts
    volumes:
      - react:/usr/app/srcs
    networks:
      - my_network
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: always
    # depends_on:
    #   - postgresql

  # nest:
  #   container_name: nest
  #   build: ./services/nest
  #   image: nest:ts
  #   volumes:
  #     - nest:/usr/app/srcs
  #   networks:
  #     - my_network
  #   ports:
  #     - "3000:3000"
  #   restart: always

  # postgresql:
  #   container_name: postgresql
  #   build:
  #     context: ./services/postgresql
  #     args:
  #       - DB_NAME=${DB_NAME}
  #       - POSTGRES_USER_ID=${POSTGRES_USER_ID}
  #       - POSTGRES_USER_PASSWORD=${POSTGRES_USER_PASSWORD}
  #   image: db:ts
  #   expose:
  #     - "5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - my_network
  #   restart: always


volumes:
  react:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '${PWD}/srcs/react'
  # nest:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: '${PWD}/srcs/nest'
  # db:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: '${PWD}/srcs/postgresql'

networks:
  my_network: 
    driver: bridge